spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mycontacts
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        id:
          new_generator_mappings: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


